core: Implemented phase 2 of IR transformations, added shallow tests
During the phase 2 of IR transformations, the instructions accessing memory
are processed as well as memory barriers of several sorts.

The existing tests have been revisited and several new test functions have
been added for the testing system to check the phase 2 too, at least, at the
"shallow" level (crash / no crash). Deeper tests should be developed in the
near future.

diff --git a/sources/core/tests/callbacks/calls/test.sh.in b/sources/core/tests/callbacks/calls/test.sh.in
--- a/sources/core/tests/callbacks/calls/test.sh.in
+++ b/sources/core/tests/callbacks/calls/test.sh.in
@@ -90,6 +90,16 @@ doTest()
 		exit 1
 	fi
 
+	# Unload the target. The test functions will be called from the 
+	# cleanup function of the target module and will produce the events
+	# to be analyzed later.
+	/sbin/rmmod "${TARGET_MODULE_NAME}"
+	if test $? -ne 0; then
+		printf "Failed to unload the target module: ${TARGET_MODULE_NAME}\n"
+		cleanupAll
+		exit 1
+	fi
+
 	# Save the information obtained by the reporter module.
 	mount -t debugfs none "${TEST_DEBUGFS_DIR}"
 	if test $? -ne 0; then
@@ -119,14 +129,7 @@ doTest()
 		exit 1
 	fi
 	
-	# Unload the modules, they are no longer needed
-	/sbin/rmmod "${TARGET_MODULE_NAME}"
-	if test $? -ne 0; then
-		printf "Failed to unload the target module: ${TARGET_MODULE_NAME}\n"
-		cleanupAll
-		exit 1
-	fi
-
+	# Unload the remaining modules, they are no longer needed
 	/sbin/rmmod "${REPORTER_MODULE_NAME}"
 	if test $? -ne 0; then
 		printf "Failed to unload the test module: ${REPORTER_MODULE_NAME}\n"
diff --git a/sources/core/tests/i13n/transform/test.sh.in b/sources/core/tests/i13n/transform/test.sh.in
--- a/sources/core/tests/i13n/transform/test.sh.in
+++ b/sources/core/tests/i13n/transform/test.sh.in
@@ -83,6 +83,16 @@ doTest()
 		cleanupAll
 		exit 1
 	fi
+	
+	# Unload the target. The test functions will be called from the 
+	# cleanup function of the target module and will produce the events
+	# to be analyzed later.
+	/sbin/rmmod "${TARGET_MODULE_NAME}"
+	if test $? -ne 0; then
+		printf "Failed to unload the target module: ${TARGET_MODULE_NAME}\n"
+		cleanupAll
+		exit 1
+	fi
 
 	# Save the information about the function of the target obtained by 
 	# the test module.
@@ -113,14 +123,7 @@ doTest()
 		exit 1
 	fi
 	
-	# Unload the modules, they are no longer needed
-	/sbin/rmmod "${TARGET_MODULE_NAME}"
-	if test $? -ne 0; then
-		printf "Failed to unload the target module: ${TARGET_MODULE_NAME}\n"
-		cleanupAll
-		exit 1
-	fi
-
+	# Unload the remaining modules, they are no longer needed
 	/sbin/rmmod "${ACCESSOR_MODULE_NAME}"
 	if test $? -ne 0; then
 		printf "Failed to unload the test module: ${ACCESSOR_MODULE_NAME}\n"
