core: The owner of the handlers is now locked in memory when needed
When the target has just loaded, the core now increases the usage count
of the module that owns the currently registered set of event handlers.
That module becomes not unloadable until the target is unloaded.

The core module is now also not unloadable when the target is in memory:
either the core is the owner of the current set of handlers or the owner
of that set is another module that uses the functions exported by the
core. The usage count of the core module will be positive in both cases
this way.

diff --git a/sources/core/tests/callbacks/load_unload/test.sh.in b/sources/core/tests/callbacks/load_unload/test.sh.in
--- a/sources/core/tests/callbacks/load_unload/test.sh.in
+++ b/sources/core/tests/callbacks/load_unload/test.sh.in
@@ -127,6 +127,21 @@ doTest()
     # 'called_load_cb' should be 1, 'called_unload_cb' should be 0
     checkIndicators 1 0
     
+    # Check that the module providing the callbacks ("test module") can not 
+    # be unloaded when the target is in memory.
+    printf "The following 'rmmod' command is expected to fail.\n"
+    /sbin/rmmod "${TEST_MODULE_NAME}"
+    if test $? -eq 0; then
+        printf "The test module (the owner of the callbacks) "
+        printf "should have been locked by the core for the time the "
+        printf "target module is in memory. It seems, it was not locked "
+        printf "because the test was able to unload the test module.\n"
+        cleanupAll
+        exit 1
+    fi
+    printf "The error above was expected, continuing the test...\n"
+    
+    # OK, now unload the target...
     printf "Checking \"target_about_to_unload\" event...\n"
     /sbin/rmmod "${TARGET_MODULE_NAME}"
     if test $? -ne 0; then
@@ -134,7 +149,6 @@ doTest()
         cleanupAll
         exit 1
     fi
-    
     
     # 'called_load_cb' should be 0, 'called_unload_cb' should be 1
     checkIndicators 0 1
